### ISSUE TITLE
Code Size

### ISSUE THREAD

**Issue by jakobotten3** [majbthrd/D21rndis#1]
Hi @majbthrd ,

I am considering using this in a project and in your readme you mentioned needing to use a SAMD21 with 32kB of RAM and at least 128kB of Flash. Can you tell me how much of this RAM and Flash it uses in a typical application? How much space would I have for other processes?

I don't currently have access to Crossworks, but i'm willing to get it if this will work for my project. 

Thanks in advance for your help.

**Comment by majbthrd** [comment]
The project as-is compiles with Rowley Crossworks 4.5.5 to be:

82.7kB of flash using GCC (79.6kB using Clang)
25.5kB of SRAM

Of the 25.5kB of SRAM, 1kB was used as the stack and 256 bytes for the heap.

Of the 82.7kB (or 79.6kB) of flash, 40.5kB was used for the assets associated with the internal web page.  Of that 40.5kB, 12.3kB is a SVG picture of a toaster and 25.3kB is the "zepto.js" Javascript inherited from the lrndis project.

So, as with any device implementing a TCP/IP stack, one of the biggest users is RAM (because TCP/IP uses tons of it... at least by embedded standards).

I'd encourage you to look at ataradov's project for examples of implementing a GCC Makefile build:

https://github.com/ataradov/mcu-starter-projects

You'll see in my stm32cdcuart, SAMC21demoCAN, NUC121usb, NUC126usb, etc. projects that I used derivatives of these (and will eventually one day do the same with this project) to support both Rowley and Makefile builds.  It is a pet peeve of mine that so many so-called "open source" firmware projects contain C startup code that is copyrighted, not open source, and has limited license terms; in contrast, ataradov's source code is genuinely open source (and why I suggest it).
